/**
 * Exhaustive path **templates** matching URLs extracted from
 * `Sofascore api documentation/*.md` (grep for `sofascore.com/api/v1/`).
 *
 * Placeholders: `{sport}`, `{id}`, `{tid}`, `{sid}`, `{date}`, `{page}`, `{cc}`,
 * `{providerId}`, `{slug}`, `{kind}`, `{round}`, `{lang}`, `{query}`, `{channelId}`,
 * `{rankingTypeId}`, `{playerId}`, `{teamId}`, `{eventId}`, `{managerId}`,
 * `{categoryId}`, `{tournamentId}` (unique-tournament id unless noted).
 *
 * Keep in sync when adding methods to `SofaContractService`.
 */
export const SOFASCORE_DOCUMENTED_PATH_TEMPLATES: readonly string[] = [
  // Sport
  "sport/{sport}/categories",
  "sport/{sport}/categories/all",
  "sport/{sport}/live-tournaments",
  "sport/{sport}/events/live",
  "sport/{sport}/scheduled-events/{date}",
  "sport/{sport}/scheduled-events/{date}/page/{page}",
  "sport/{sport}/scheduled-events/{date}",
  "sport/{numericId}/event-count",
  "sport/{sport}/trending-top-players",
  "sport/{sport}/live-categories",
  "sport/{sport}/{date}/{segmentId}/categories",
  // Unique tournament (root + season)
  "unique-tournament/{tid}",
  "unique-tournament/{tid}/winners",
  "unique-tournament/{tid}/seasons",
  "unique-tournament/{tid}/scheduled-events/{date}",
  "unique-tournament/{tid}/featured-events",
  "unique-tournament/{tid}/media",
  "unique-tournament/{tid}/season/{sid}/standings/total",
  "unique-tournament/{tid}/season/{sid}/standings/home",
  "unique-tournament/{tid}/season/{sid}/standings/away",
  "unique-tournament/{tid}/season/{sid}/groups",
  "unique-tournament/{tid}/season/{sid}/venues",
  "unique-tournament/{tid}/season/{sid}/rounds",
  "unique-tournament/{tid}/season/{sid}/info",
  "unique-tournament/{tid}/season/{sid}/cuptrees",
  "unique-tournament/{tid}/season/{sid}/team-events/total",
  "unique-tournament/{tid}/season/{sid}/events/next/{page}",
  "unique-tournament/{tid}/season/{sid}/events/round/{round}",
  "unique-tournament/{tid}/season/{sid}/events/round/{round}/slug/{slug}",
  "unique-tournament/{tid}/season/{sid}/editors",
  "unique-tournament/{tid}/season/{sid}/top-players/overall",
  "unique-tournament/{tid}/season/{sid}/top-players/rating",
  "unique-tournament/{tid}/season/{sid}/top-players/goals",
  "unique-tournament/{tid}/season/{sid}/top-players/{slug}",
  "unique-tournament/{tid}/season/{sid}/top-players-per-game/all/overall",
  "unique-tournament/{tid}/season/{sid}/top-ratings/overall",
  "unique-tournament/{tid}/season/{sid}/top-teams/overall",
  "unique-tournament/{tid}/season/{sid}/player-statistics/types",
  "unique-tournament/{tid}/season/{sid}/power-rankings/rounds",
  "unique-tournament/{tid}/season/{sid}/team-of-the-week/rounds",
  "unique-tournament/{tid}/season/{sid}/team-of-the-week/{round}",
  "unique-tournament/{tid}/season/{sid}/team-of-the-week/periods",
  "unique-tournament/{tid}/season/{sid}/player-of-the-season",
  // Non-unique tournament (competition id)
  "tournament/{tid}/season/{sid}/standings/total",
  //23
  "tournament/{tid}/season/{sid}/standings/home",
  "tournament/{tid}/season/{sid}/standings/away",
  "category/{categoryId}/unique-tournaments",
  // Event
  "event/{eventId}",
  "event/{eventId}/incidents",
  "event/{eventId}/statistics",
  "event/{eventId}/lineups",
  "event/{eventId}/shotmap",
  "event/{eventId}/shotmap/{teamId}",
  "event/{eventId}/heatmap/{teamId}",
  // "event/{eventId}/graph/win-probability",
  "event/{eventId}/graph",
  "event/{eventId}/point-by-point",
  "event/{eventId}/points/overview",
  "event/{eventId}/innings",
  // "event/{eventId}/pregame-form",
  "event/{eventId}/h2h",
  "event/{eventId}/h2h/events",
  "event/{eventId}/team-streaks",
  "event/{eventId}/team-streaks/betting-odds/{providerId}",
  "event/{eventId}/best-players",
  "event/{eventId}/best-players/summary",
  "event/{eventId}/managers",
  "event/{eventId}/highlights",
  "event/{eventId}/votes",
  "event/{eventId}/comments",
  "event/{eventId}/official-tweets",
  // "event/{eventId}/ai-insights/{lang}",
  "event/{eventId}/meta",
  "event/{eventId}/media/summary/country/{cc}",
  "event/{eventId}/odds/{providerId}/featured",
  "event/{eventId}/odds/{providerId}/all",
  "event/{eventId}/provider/{providerId}/winning-odds",
  "event/newly-added-events",
  "tv/event/{eventId}/country-channels",
  "tv/channel/{channelId}/schedule",
  // Team
  "team/{teamId}",
  "team/{teamId}/rankings",
  "team/{teamId}/team-statistics/seasons",
  "team/{teamId}/recent-unique-tournaments",
  "team/{teamId}/unique-tournaments",
  "team/{teamId}/unique-tournaments/all",
  "team/{teamId}/performance",
  "team/{teamId}/featured-event",
  "team/{teamId}/featured-players",
  "team/{teamId}/players",
  "team/{teamId}/near-events",
  "team/{teamId}/events/next/{page}",
  "team/{teamId}/events/last/{page}",
  "team/{teamId}/transfers",
  "team/{teamId}/media",
  "team/{teamId}/media/summary/country/{cc}",
  "team/{teamId}/achievements",
  "team/{teamId}/grand-slam/best-results",
  "team/{teamId}/standings/seasons",
  "team/{teamId}/unique-tournament/{tid}/season/{sid}/statistics/overall",
  "team/{teamId}/unique-tournament/{tid}/season/{sid}/statistics/home",
  "team/{teamId}/unique-tournament/{tid}/season/{sid}/statistics/away",
  "team/{teamId}/unique-tournament/{tid}/season/{sid}/player-statistics/{kind}",
  "team/{teamId}/unique-tournament/{tid}/season/{sid}/top-players/overall",
  "team/{teamId}/unique-tournament/{tid}/season/{sid}/top-players/home",
  "team/{teamId}/unique-tournament/{tid}/season/{sid}/top-players/away",
  "team/{teamId}/unique-tournament/{tid}/season/{sid}/top-players/{slug}",
  "team/{teamId}/unique-tournament/{tid}/season/{sid}/goal-distributions",
  "unique-tournament/{tid}/season/{sid}/team/{teamId}/team-performance-graph-data",
  "player/{playerId}/season/{sid}/statistical-rankings/{slug}",
  // Player / manager / fantasy
  "player/{playerId}",
  "player/{playerId}/performance",
  "player/{playerId}/statistics",
  "player/{playerId}/statistics/seasons",
  "player/{playerId}/last-year-summary",
  "player/{playerId}/unique-tournaments",
  "player/{playerId}/unique-tournament/{tid}/season/{sid}/statistics/overall",
  "player/{playerId}/transfer-history",
  "player/{playerId}/national-team-statistics",
  "player/{playerId}/attribute-overviews",
  "player/{playerId}/events/last/{page}",
  "player/{playerId}/media",
  "player/{playerId}/media/videos",
  "fantasy/player/{playerId}/competitions",
  "manager/{managerId}",
  "manager/{managerId}/career-history",
  // Config / odds / branding / news / search / rankings
  "country/alpha2",
  "config/country-sport-priorities/country",
  "config/country-sport-priorities/country/{cc}",
  "config/default-unique-tournaments/{cc}/{sport}",
  "config/top-unique-tournaments/{cc}/{sport}",
  "odds/providers/{cc}/web",
  "odds/providers/{cc}/web-odds",
  "odds/providers/{cc}/web-featured",
  "branding/providers/{cc}/web",
  "odds/top-team-streaks/wins/all",
  "odds/{providerId}/featured-events/{sport}",
  "odds/{providerId}/featured-events-by-popularity/{sport}",
  // "sofascore-news/{lang}/posts",
  "search/all/?q={query}&page={page}",
  "search/events/?q={query}&page={page}",
  "search/player-team-persons/?q={query}&page={page}",
  "search/teams/?q={query}&page={page}",
  "search/unique-tournaments/?q={query}&page={page}",
  "search/suggestions/default",
  "rankings/type/{rankingTypeId}",
];
